# Generated by Django 6.1.1 on 2026-10-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Informação",
            new_name="Informacao",
        ),
    ]
